#pragma once

namespace Sim {

enum class RequestType {
  PUSHBACK_START,
  PUSHBACK_COMPLETE,
  ENGINE_STARTED,
  READY_TO_TAXI,
  HOLD_SHORT_REACHED,
  LINE_UP_REACHED,
  RUNWAY_CROSSED,
  BACK_TAXI_COMPLETE,
  AT_GATE,
  AT_RAMP,
  AT_HANGAR,

  TAKEOFF_ROLL_START,
  ROTATION,
  CLIMBOUT_ESTABLISHED,
  CONTACT_DEPARTURE,
  CLIMBING_VIA_SID,

  WAYPOINT_CROSSED,
  ALTITUDE_REACHED,
  SPEED_REACHED,
  HEADING_REACHED,
  DIRECT_TO_COMPLETE,
  ESTABLISHED_ON_COURSE,

  HOLDING_ENTRY_STARTED,
  HOLDING_ESTABLISHED,
  HOLDING_EXITED,
  EFC_RECEIVED,

  STARTING_DESCENT,
  DESCEND_VIA_STAR,
  APPROACH_CLEARANCE_REQUIRED,
  INITIAL_APPROACH_FIX,
  FINAL_APPROACH_FIX,
  ESTABLISHED_LOCALIZER,
  ESTABLISHED_GLIDESLOPE,
  ESTABLISHED_FINAL,
  OUTER_MARKER,
  MIDDLE_MARKER,
  DECISION_ALTITUDE,
  MINIMUM_DESCENT_ALTITUDE,

  CLEARED_TO_LAND,
  FLARE,
  TOUCHDOWN,
  ROLLOUT,
  VACATED_RUNWAY,
  REACHED_GATE,
  REACHED_RAMP,
  REACHED_HANGAR,

  GO_AROUND_INITIATED,
  MISSED_APPROACH_INITIATED,
  MISSED_APPROACH_PUBLISHED,
  GO_AROUND_COMPLETE,

  TOUCH_AND_GO_INITIATED,
  STOP_AND_GO_INITIATED,

  POSITION_REPORT,
  CTAF_CALL,

  MAYDAY_DECLARED,
  PAN_PAN_DECLARED,
  EMERGENCY_DESCENT_STARTED,
  EMERGENCY_LANDING_REQUIRED,
  EMERGENCY_CANCELLED,
  MINIMUM_FUEL,
  RADIO_FAILURE,
  NORDO_PROCEDURE_ACTIVATED,
  SQUAWK_7700,
  SQUAWK_7600,
  SQUAWK_7500,
  DIVERSION_REQUIRED,

  FREQUENCY_CHANGED,
  CONTACT_MADE,
  READBACK_RECEIVED,
  UNABLE_TO_COMPLY,
  STANDING_BY,

  HANDOFF_COMPLETE,
  ASSUMED_CONTROL,
  RELEASED_CONTROL,

  COLLISION_WARNING,
  SEPARATION_ALERT,
  CONFLICT_ALERT,
  TERRAIN_ALERT,
  AIRSPACE_VIOLATION,
  CLEARANCE_AMENDMENT,
};

} // namespace Sim
