#pragma once

namespace Sim {

enum class WaypointType {
  NORMAL,
  HOLD_SHORT,
  RUNWAY_THRESHOLD,
  GATE,
  RAMP,
  HANGAR,
  HOLDING_FIX,
  INITIAL_APPROACH_FIX,
  FINAL_APPROACH_FIX,
  MISSED_APPROACH_POINT,
  OUTER_MARKER,
  MIDDLE_MARKER,
  INNER_MARKER,
  TURN_POINT,
  SID_WAYPOINT,
  STAR_WAYPOINT,
  CROSSING_RESTRICTION,
  RUNWAY_EXIT,
  HANDOFF_POINT,
  POSITION_REPORT_POINT,
};

} // namespace Sim
